# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0016_alter_model_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='logging_dir',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Logging Directory'),
        ),
    ]
